const crypto = require("crypto");


// =====================================================
// NOVAPAY ADMIN MANAGEMENT SYSTEM
// ADMIN CONFIGURATION
// =====================================================
//
// This file contains the server-side configuration for
// the Admin Management System.
//
// IMPORTANT:
// - This file is backend-only.
// - Never send these values to the frontend.
// - Never commit real admin secrets to GitHub.
// - The initial admin token is generated by the backend.
// - The raw admin token is never stored in Firestore.
// =====================================================


// =====================================================
// REQUIRED INITIAL ADMIN CONFIGURATION
// =====================================================
//
// The initial administrator is established by the
// backend configuration.
//
// superAdmin
//   The configured superAdmin identifier.
//
// adminUid
//   The permanent UID belonging to the administrator.
//
// The initial admin token is NOT stored here.
// It is generated securely by the backend during the
// first Admin Management System bootstrap.
// =====================================================

const superAdmin =
  "superAdmin";

const adminUid =
  "ikj1hoaR3fNuVeMBKDCAp5VOrzm1z";


// =====================================================
// VALIDATE REQUIRED CONFIGURATION
// =====================================================

if (!superAdmin) {
  throw new Error(
    "Initial superAdmin is not configured."
  );
}

if (!adminUid) {
  throw new Error(
    "Initial admin UID is not configured."
  );
}


// =====================================================
// ADMIN SYSTEM SETTINGS
// =====================================================

const adminConfig = {

  // ---------------------------------------------------
  // INITIAL ADMIN
  // ---------------------------------------------------

  superAdmin,

  uid: adminUid,

  role: "superAdmin",

  status: "active",


  // ---------------------------------------------------
  // TOKEN
  // ---------------------------------------------------
  //
  // 16 random bytes converted to hexadecimal produce
  // exactly 32 characters.
  //
  // The token itself is generated by the backend.
  // ---------------------------------------------------

  tokenBytes: 16,

  tokenLength: 32,

  tokenEncoding: "hex",


  // ---------------------------------------------------
  // LOGIN SECURITY
  // ---------------------------------------------------

  maxFailedAttempts: 3,

  lockoutMinutes: 30,


  // ---------------------------------------------------
  // ACTIVE DEVICE SECURITY
  // ---------------------------------------------------
  //
  // Only one active admin device/session is permitted
  // at a time.
  // ---------------------------------------------------

  allowMultipleActiveDevices: false,


  // ---------------------------------------------------
  // TOKEN SECURITY
  // ---------------------------------------------------

  tokenHashAlgorithm: "sha256"
};


// =====================================================
// TOKEN HASH HELPER
// =====================================================
//
// This helper converts a token into a one-way hash.
//
// The raw token should not be stored in Firestore.
// =====================================================

function hashAdminToken(token) {

  if (
    typeof token !== "string" ||
    !token
  ) {
    throw new Error(
      "Admin token is required."
    );
  }

  return crypto
    .createHash(
      adminConfig.tokenHashAlgorithm
    )
    .update(token, "utf8")
    .digest("hex");
}


// =====================================================
// TOKEN GENERATOR
// =====================================================
//
// Generates a cryptographically secure admin token.
//
// 16 random bytes -> exactly 32 hexadecimal
// characters.
//
// The raw generated token will only be available to
// the backend process that creates or rotates it.
// =====================================================

function generateAdminToken() {

  return crypto
    .randomBytes(
      adminConfig.tokenBytes
    )
    .toString(
      adminConfig.tokenEncoding
    );
}


// =====================================================
// EXPORTS
// =====================================================

module.exports = {
  adminConfig,
  hashAdminToken,
  generateAdminToken
};