// add-money/paystack/provider.js

/**
 * NovaPay Paystack Payment Provider
 *
 * This file contains ALL Paystack-specific Add Money logic.
 *
 * routes.js does not need to know how Paystack works.
 *
 * Pay with Transfer:
 * - Creates a temporary bank account for one transaction.
 * - The account expires according to the expiry time.
 * - The returned account details are passed back to routes.js.
 *
 * IMPORTANT:
 * PAYSTACK_SECRET_KEY must exist in the server environment.
 * Never put the secret key directly in this file.
 */

const PAYSTACK_API_URL =
    "https://api.paystack.co";


// =====================================================
// CONFIGURATION
// =====================================================

const PAYSTACK_SECRET_KEY =
    String(
        process.env.PAYSTACK_SECRET_KEY || ""
    ).trim();


// =====================================================
// VALIDATE CONFIGURATION
// =====================================================

function requirePaystackSecretKey() {

    if (!PAYSTACK_SECRET_KEY) {

        throw new Error(
            "PAYSTACK_SECRET_KEY is not configured."
        );
    }

}


// =====================================================
// PAYSTACK API REQUEST
// =====================================================

async function paystackRequest(
    endpoint,
    options = {}
) {

    requirePaystackSecretKey();


    const response =
        await fetch(
            `${PAYSTACK_API_URL}${endpoint}`,
            {
                method:
                    options.method ||
                    "GET",

                headers: {

                    "Authorization":
                        `Bearer ${PAYSTACK_SECRET_KEY}`,

                    "Content-Type":
                        "application/json",

                    "Accept":
                        "application/json"
                },

                body:
                    options.body
                        ? JSON.stringify(
                            options.body
                        )
                        : undefined
            }
        );


    let result = null;


    try {

        result =
            await response.json();

    } catch {

        result =
            null;
    }


    if (!response.ok) {

        const message =
            result?.message ||
            "Paystack request failed.";

        const error =
            new Error(
                message
            );

        error.status =
            response.status;

        error.response =
            result;

        throw error;
    }


    if (
        !result ||
        result.status !== true
    ) {

        const error =
            new Error(
                result?.message ||
                "Paystack rejected the request."
            );

        error.response =
            result;

        throw error;
    }


    return result;
}


// =====================================================
// CREATE PAYMENT SESSION
// =====================================================
//
// Creates a Paystack Pay-with-Transfer charge.
//
// The account generated by Paystack is temporary and
// belongs to this specific transaction.
//
// =====================================================

async function createPaymentSession(
    {
        email,
        amount,
        reference,
        accountExpiresAt
    }
) {

    if (!email) {

        throw new Error(
            "Payment email is required."
        );
    }


    if (
        !Number.isSafeInteger(
            amount
        ) ||
        amount <= 0
    ) {

        throw new Error(
            "Payment amount must be a valid positive integer in kobo."
        );
    }


    if (!reference) {

        throw new Error(
            "Payment reference is required."
        );
    }


    /*
     * Paystack requires the expiry to be at least
     * 15 minutes from the current time and no more
     * than 8 hours from the current time.
     *
     * We use 1 hour by default.
     */

    let expiry =
        accountExpiresAt;


    if (!expiry) {

        expiry =
            new Date(
                Date.now() +
                60 * 60 * 1000
            ).toISOString();
    }


    const result =
        await paystackRequest(
            "/charge",
            {
                method:
                    "POST",

                body: {

                    email,

                    amount:
                        String(
                            amount
                        ),

                    reference,

                    bank_transfer: {

                        account_expires_at:
                            expiry

                    }
                }
            }
        );


    const payment =
        result.data;


    if (!payment) {

        throw new Error(
            "Paystack returned an empty payment response."
        );
    }


    /*
     * Make sure Paystack actually created
     * the temporary transfer account.
     */

    if (
        !payment.account_number ||
        !payment.account_name ||
        !payment.bank
    ) {

        throw new Error(
            "Paystack did not return temporary transfer account details."
        );
    }


    return {

        reference:
            payment.reference ||
            reference,

        status:
            payment.status ||
            "pending_bank_transfer",

        accountName:
            payment.account_name ||
            null,

        accountNumber:
            payment.account_number ||
            null,

        bankName:
            payment.bank?.name ||
            null,

        bankCode:
            payment.bank?.slug ||
            null,

        accountExpiresAt:
            payment.account_expires_at ||
            expiry

    };
}


// =====================================================
// VERIFY PAYMENT
// =====================================================
//
// This is intentionally separate from creating the
// payment.
//
// Later the webhook/crediting system can call this
// function when it needs to confirm a transaction.
//
// =====================================================

async function verifyPayment(
    reference
) {

    if (!reference) {

        throw new Error(
            "Payment reference is required."
        );
    }


    const encodedReference =
        encodeURIComponent(
            reference
        );


    const result =
        await paystackRequest(
            `/transaction/verify/${encodedReference}`,
            {
                method:
                    "GET"
            }
        );


    const transaction =
        result.data;


    if (!transaction) {

        throw new Error(
            "Paystack returned an empty verification response."
        );
    }


    return {

        reference:
            transaction.reference ||
            reference,

        status:
            transaction.status ||
            "unknown",

        amount:
            Number(
                transaction.amount
            ),

        currency:
            transaction.currency ||
            "NGN",

        paidAt:
            transaction.paid_at ||
            null,

        channel:
            transaction.channel ||
            null,

        gatewayResponse:
            transaction.gateway_response ||
            null

    };
}


// =====================================================
// EXPORTS
// =====================================================

module.exports = {

    createPaymentSession,

    verifyPayment

};