const {
  adminConfig
} = require("../config/adminConfig");

const {
  createTokenCredential
} = require("./adminTokenService");

const {
  createInitialSuperAdmin,
  getSuperAdmin
} = require("./adminCredentialStore");


// =====================================================
// ADMIN BOOTSTRAP
// =====================================================
//
// This file performs the one-time initial setup of the
// NovaPay Admin Management System.
//
// IMPORTANT:
//
// - There is NO admin registration system.
// - This does NOT create admins through an API.
// - Existing Firestore credentials are never replaced.
// - The initial token is generated by the backend.
// - Only the token hash is stored in Firestore.
// - The raw initial token is displayed only when the
//   admin record is created for the first time.
// =====================================================


// -----------------------------------------------------
// INITIALIZE ADMIN SYSTEM
// -----------------------------------------------------

async function initializeAdminSystem() {

  // ---------------------------------------------------
  // CHECK WHETHER ADMIN ALREADY EXISTS
  // ---------------------------------------------------

  const existingAdmin =
    await getSuperAdmin();

  if (existingAdmin) {

    return {
      initialized: false,
      alreadyInitialized: true
    };
  }


  // ---------------------------------------------------
  // GENERATE INITIAL ADMIN TOKEN
  // ---------------------------------------------------
  //
  // The token service generates exactly 32 characters
  // and creates its secure hash.
  //
  // The raw token is kept only in memory during this
  // bootstrap operation.
  // ---------------------------------------------------

  const {
    token: initialToken,
    tokenHash
  } = createTokenCredential();


  // ---------------------------------------------------
  // CREATE INITIAL SUPER ADMIN
  // ---------------------------------------------------
  //
  // Only the token hash is passed for storage.
  // The raw token is never stored in Firestore.
  // ---------------------------------------------------

  const result =
    await createInitialSuperAdmin({
      superAdmin:
        adminConfig.superAdmin,

      adminUid:
        adminConfig.uid,

      tokenHash
    });


  // ---------------------------------------------------
  // HANDLE RACE CONDITION
  // ---------------------------------------------------
  //
  // If another server instance created the admin
  // between our initial check and create operation,
  // do not expose the newly generated token because
  // it would not belong to the stored administrator.
  // ---------------------------------------------------

  if (!result.created) {

    return {
      initialized: false,
      alreadyInitialized: true
    };
  }


  // ---------------------------------------------------
  // DISPLAY INITIAL TOKEN ON FIRST BOOTSTRAP
  // ---------------------------------------------------
  //
  // This is the ONLY time the raw initial token is
  // displayed by this bootstrap process.
  //
  // IMPORTANT:
  // Copy the token from the backend startup log and
  // keep it secure.
  // ---------------------------------------------------

  console.log("");
  console.log("=====================================================");
  console.log("NOVAPAY ADMIN SYSTEM INITIALIZED");
  console.log("=====================================================");
  console.log(
    "superAdmin:",
    adminConfig.superAdmin
  );
  console.log(
    "Initial Admin Token:",
    initialToken
  );
  console.log(
    "Token Length:",
    initialToken.length
  );
  console.log("=====================================================");
  console.log(
    "IMPORTANT: Store this token securely."
  );
  console.log(
    "It will NOT be shown again on future server restarts."
  );
  console.log("=====================================================");
  console.log("");


  // ---------------------------------------------------
  // RETURN SAFE STATUS ONLY
  // ---------------------------------------------------
  //
  // Do NOT return:
  // - raw token
  // - token hash
  // - UID
  // - secret configuration
  // ---------------------------------------------------

  return {
    initialized: true,
    alreadyInitialized: false
  };
}


// -----------------------------------------------------
// EXPORTS
// -----------------------------------------------------

module.exports = {
  initializeAdminSystem
};